-- MySQL Script generated by MySQL Workbench
-- Sun Dec 11 11:13:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nc0459
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nc0459
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nc0459` DEFAULT CHARACTER SET utf8 ;
USE `nc0459` ;

-- -----------------------------------------------------
-- Table `nc0459`.`LoginDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nc0459`.`LoginDetails` (
  `LoginId` VARCHAR(10) NOT NULL,
  `emailId` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`LoginId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nc0459`.`CarOwner_NagaC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nc0459`.`CarOwner_NagaC` (
  `ID` VARCHAR(10) NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `PhoneNumber` VARCHAR(20) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `GovernmentID` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(25) NOT NULL,
  `JoinDate` DATE NOT NULL,
  `LoginId` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `LoginId_idx` (`LoginId` ASC) VISIBLE,
  CONSTRAINT `LoginId`
    FOREIGN KEY (`LoginId`)
    REFERENCES `nc0459`.`LoginDetails` (`LoginId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nc0459`.`CarRentalTuro_NagaC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nc0459`.`CarRentalTuro_NagaC` (
  `ID` VARCHAR(10) NOT NULL,
  `CarOwner_NagaC_ID` VARCHAR(10) NOT NULL,
  `CarName` VARCHAR(80) NOT NULL,
  `CarModel` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `Ratings` FLOAT NOT NULL,
  `Doors` INT NOT NULL,
  `Seats` INT NOT NULL,
  `Mileage` VARCHAR(10) NOT NULL,
  `Location` VARCHAR(50) NOT NULL,
  `CostPerDay` VARCHAR(100) NOT NULL,
  `CarType` VARCHAR(45) NOT NULL,
  `FuelType` VARCHAR(45) NOT NULL,
  `GearType` VARCHAR(45) NOT NULL,
  `JoinDate` DATE NULL,
  PRIMARY KEY (`ID`, `CarOwner_NagaC_ID`),
  INDEX `fk_CarRentalTuro_NagaC_CarOwner_NagaC1_idx` (`CarOwner_NagaC_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CarRentalTuro_NagaC_CarOwner_NagaC1`
    FOREIGN KEY (`CarOwner_NagaC_ID`)
    REFERENCES `nc0459`.`CarOwner_NagaC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nc0459`.`Customer_NagaC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nc0459`.`Customer_NagaC` (
  `ID` VARCHAR(10) NOT NULL,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `GovernmentID` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(25) NOT NULL,
  `PhoneNumber` VARCHAR(25) NOT NULL,
  `LoginID` VARCHAR(10) NOT NULL,
  `CreateDate` DATE NOT NULL,
  `UpdateDate` DATE NULL,
  PRIMARY KEY (`ID`),
  INDEX `loginId_idx` (`LoginID` ASC) VISIBLE,
  CONSTRAINT `log_Id`
    FOREIGN KEY (`LoginID`)
    REFERENCES `nc0459`.`LoginDetails` (`LoginId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nc0459`.`Reviews_NagaC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nc0459`.`Reviews_NagaC` (
  `ID` VARCHAR(10) NOT NULL,
  `Ratings` FLOAT NOT NULL,
  `Comments` VARCHAR(500) NULL,
  `BookingID` VARCHAR(45) NOT NULL,
  `Customer_NagaC_ID` VARCHAR(10) NOT NULL,
  `CarOwner_NagaC_ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`, `Customer_NagaC_ID`, `CarOwner_NagaC_ID`),
  INDEX `fk_Reviews_NagaC_Customer_NagaC_idx` (`Customer_NagaC_ID` ASC) VISIBLE,
  INDEX `fk_Reviews_NagaC_CarOwner_NagaC1_idx` (`CarOwner_NagaC_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reviews_NagaC_Customer_NagaC`
    FOREIGN KEY (`Customer_NagaC_ID`)
    REFERENCES `nc0459`.`Customer_NagaC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reviews_NagaC_CarOwner_NagaC1`
    FOREIGN KEY (`CarOwner_NagaC_ID`)
    REFERENCES `nc0459`.`CarOwner_NagaC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nc0459`.`Bookings_NagaC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nc0459`.`Bookings_NagaC` (
  `BookingID` VARCHAR(45) NOT NULL,
  `CarOwner_NagaC_ID` VARCHAR(10) NOT NULL,
  `PickupDate` DATETIME NOT NULL,
  `ReturnDate` DATETIME NOT NULL,
  `PricePerDay` FLOAT NOT NULL,
  `TotalBookingDays` INT NOT NULL,
  `ServiceFee` FLOAT NOT NULL,
  `Taxes` FLOAT NOT NULL,
  `TotalCost` FLOAT NOT NULL,
  `Reviews_NagaC_ID` VARCHAR(10) NOT NULL,
  `Reviews_NagaC_Customer_NagaC_ID` VARCHAR(10) NOT NULL,
  `CarRentalTuro_NagaC_ID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`BookingID`, `CarOwner_NagaC_ID`, `Reviews_NagaC_ID`, `Reviews_NagaC_Customer_NagaC_ID`, `CarRentalTuro_NagaC_ID`),
  INDEX `fk_Bookings_NagaC_Reviews_NagaC1_idx` (`Reviews_NagaC_ID` ASC, `Reviews_NagaC_Customer_NagaC_ID` ASC) VISIBLE,
  INDEX `fk_Bookings_NagaC_CarOwner_NagaC1_idx` (`CarOwner_NagaC_ID` ASC) VISIBLE,
  INDEX `fk_Bookings_NagaC_CarRentalTuro_NagaC1_idx` (`CarRentalTuro_NagaC_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bookings_NagaC_Reviews_NagaC1`
    FOREIGN KEY (`Reviews_NagaC_ID` , `Reviews_NagaC_Customer_NagaC_ID`)
    REFERENCES `nc0459`.`Reviews_NagaC` (`ID` , `Customer_NagaC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_NagaC_CarOwner_NagaC1`
    FOREIGN KEY (`CarOwner_NagaC_ID`)
    REFERENCES `nc0459`.`CarOwner_NagaC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_NagaC_CarRentalTuro_NagaC1`
    FOREIGN KEY (`CarRentalTuro_NagaC_ID`)
    REFERENCES `nc0459`.`CarRentalTuro_NagaC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
